### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by Maxime5G** [aidantay/Synsor#1]
Hello,

I tried using synsor on one test data referenced in the paper [(this one).](https://trace.ncbi.nlm.nih.gov/Traces/?view=run_browser&acc=ERR1938686&display=metadata) but it returned a ZeroDivisionError.

I created the synsor conda environment as written in the readme file, assembled the paired-end reads using SPAdes 3.15.5 and applied synsor on the resulting contigs using those two commands as referenced in the readme:

```
python synsor.py count -i assembly/contigs.fasta -k 7 -o test
python synsor.py predict -f test -m Synsor/model -o output.tsv
```

Here's the (full) error message:

```
2024-08-19 13:53:21.181794: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
venv/synsor/lib/python3.10/site-packages/dask/dataframe/_pyarrow_compat.py:15: FutureWarning: Minimal version of pyarrow will soon be increased to 14.0.1. You are using 9.0.0. Please consider upgrading.
  warnings.warn(
Predicting sequence class
No active Spark session. Reading with Dask
2024-08-19 13:53:24.860061: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "Synsor/synsor.py", line 116, in <module>
    args.func(args)
  File "Synsor/synsor.py", line 52, in predict
    predict_engineered_sequences.main(args.f, [args.m], args.o)
  File "Synsor/src/jobs/predict_engineered_sequences.py", line 28, in main
    kmerDf = _prepareData(kmerDf)
  File "Synsor/src/jobs/predict_engineered_sequences.py", line 87, in _prepareData
    kmerCount = kmerCount.compute()
  File "venv/synsor/lib/python3.10/site-packages/dask_expr/_collection.py", line 476, in compute
    return DaskMethodsMixin.compute(out, **kwargs)
  File "venv/synsor/lib/python3.10/site-packages/dask/base.py", line 376, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "venv/synsor/lib/python3.10/site-packages/dask/base.py", line 662, in compute
    results = schedule(dsk, keys, **kwargs)
  File "venv/synsor/lib/python3.10/site-packages/dask_expr/_expr.py", line 3758, in _execute_task
    return dask.core.get(graph, name)
  File "venv/synsor/lib/python3.10/site-packages/pandas/core/computation/expressions.py", line 73, in _evaluate_standard
    return op(a, b)
ZeroDivisionError: float division by zero
```
The assembled contigs are: [contigs_for_synsor.zip](https://github.com/user-attachments/files/16659936/contigs_for_synsor.zip).

Do you have an idea of what went wrong?

**Comment by aidantay** [comment]
Hi @Maxime5G,

Not sure why it happens with your data in particular, but one of the columns gets incorrectly typed which then raises the error.

I've update the repo with the fix.
